// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6TPvxpKnDj8WixiIK3GL89X-T2Ycmv4',
    appId: '1:668578903392:web:4f602d465ff52fe3b95a05',
    messagingSenderId: '668578903392',
    projectId: 'ecs198f-final-project',
    authDomain: 'ecs198f-final-project.firebaseapp.com',
    storageBucket: 'ecs198f-final-project.appspot.com',
    measurementId: 'G-K5E1FC5TY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRfloA-2WbuLZ70aWexA04-dJxUoHGCk',
    appId: '1:668578903392:android:2cd9fde9333397b4b95a05',
    messagingSenderId: '668578903392',
    projectId: 'ecs198f-final-project',
    storageBucket: 'ecs198f-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8VXUb0KiIrn1iMHrDWB-MhsL5Df2BqA',
    appId: '1:668578903392:ios:3cc1e607375f2507b95a05',
    messagingSenderId: '668578903392',
    projectId: 'ecs198f-final-project',
    storageBucket: 'ecs198f-final-project.appspot.com',
    iosClientId: '668578903392-skiuuiqb8n94a5ant4o5mrjopm286mo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8VXUb0KiIrn1iMHrDWB-MhsL5Df2BqA',
    appId: '1:668578903392:ios:3cc1e607375f2507b95a05',
    messagingSenderId: '668578903392',
    projectId: 'ecs198f-final-project',
    storageBucket: 'ecs198f-final-project.appspot.com',
    iosClientId: '668578903392-skiuuiqb8n94a5ant4o5mrjopm286mo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );
}
